spring:
  security:
    oauth2:
      client:
        registration:
          kakao:
            client-id: 6177fc656fa1246c335661de82524c08
            client-secret: dKCAeB3qrJ3pvCduju9YIJBkjQnacjOU
            client-authentication-method: client_secret_post
            redirect-uri: http://localhost:8080/login/oauth2/code/kakao
            client-name: kakao
            authorization-grant-type: authorization_code
            scope:
              - profile_nickname
        provider:
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize?prompt=select_account
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id
