spring:
  application:
    name: oauth2
  profiles:
    include: oauth
  datasource:
    url: jdbc:mysql://localhost:3307/oauth
    username: root
    password: 1234
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create